### ISSUE TITLE
Update repo name

### ISSUE THREAD

**Issue by hhkaos** [EsriDevEvents/arcgis-maps-sdk-for-javascript-bring-in-data-from-anywhere#1]
@Calin-Geoinfo would you mind changing the repo name to `arcgis-maps-sdk-for-javascript-bring-in-data-from-anywhere-2023` to follow the conventions? I know its very verbose/long, but that was [the convention]( https://github.com/EsriDevEvents/contributor-guides/blob/main/conventions.md#conventions-for-repositories).

**Comment by Calin-Geoinfo** [comment]
Hi Raul

What about the ds-europe-2023 part, it says at the bottom of the convention that it should be added as well?

/Calin

From: Raul Jimenez Ortega ***@***.***>
Sent: 9. november 2023 14:30
To: EsriDevEvents/ds-europe-2023-data-from-anywhere ***@***.***>
Cc: Calin Arens ***@***.***>; Mention ***@***.***>
Subject: [EsriDevEvents/ds-europe-2023-data-from-anywhere] Update repo name (Issue #1)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@Calin-Geoinfo<https://github.com/Calin-Geoinfo> would you mind changing the repo name to arcgis-maps-sdk-for-javascript-bring-in-data-from-anywhere to follow the conventions? I know its very verbose/long, but that was the convention<https://github.com/EsriDevEvents/contributor-guides/blob/main/conventions.md#conventions-for-repositories>.

**Comment by hhkaos** [comment]
Those are repository topics (a.k.a. talks) 😄 

You can use: `esri-devsummit` `ds-europe` `ds-2023` `esri` `arcgis` `technical-session talk`:

![2023-11-09_14-40-53](https://github.com/EsriDevEvents/ds-europe-2023-data-from-anywhere/assets/826965/3df76334-4ed1-45b4-8154-3c2bc05c7931)

**Comment by Calin-Geoinfo** [comment]
Ah ok, never worked with Github before, didn’t get the “topics” part. I’ll rename

**Comment by hhkaos** [comment]
hehe don't worry, and thanks! I'll see you in a few days!
